name: meachou
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.0.0
  provider: ^6.1.2
  skeleton_text: ^3.0.1
  confetti: ^0.7.0
  intl: ^0.19.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png
    - assets/logo.png
    - assets/background_image.jpg
    - assets/no_stores.png

