name: meachou
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  step_progress_indicator: ^1.0.2
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.0.0
  provider: ^6.1.2
  skeleton_text: ^3.0.1
  confetti: ^0.7.0
  intl: ^0.19.0
  photo_view: ^0.15.0
  flutter_typeahead: ^4.0.0
  diacritic: ^0.1.1
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0
  image_picker: ^1.1.2
  flutter_masked_text2: ^0.9.1
  lottie: ^3.1.2
  cpf_cnpj_validator: ^2.0.0
  credit_card_validator: ^2.1.0
  image: ^3.0.1
  url_launcher: ^6.0.20
  shimmer: ^2.0.0
  google_maps_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png
    - assets/finder-logo.png
    - assets/background_image.jpg
    - assets/no_stores.png
    - assets/animation/
